package io.github.sefiraat.networks.network;

public enum NodeType {
    CONTROLLER,
    BRIDGE,
    STORAGE_MONITOR,
    IMPORT,
    EXPORT,
    GRID,
    CELL,
    WIPER,
    GRABBER,
    PUSHER,
    CUTTER,
    PASTER,
    VACUUM,
    PURGER,
    CRAFTER,
    POWER_NODE,
    POWER_OUTLET,
    POWER_DISPLAY,
    ENCODER,
    GREEDY_BLOCK,
    WIRELESS_TRANSMITTER,
    WIRELESS_RECEIVER,

    // from networks expansion
    LINE_TRANSMITTER,
    LINE_TRANSMITTER_PUSHER,
    LINE_TRANSMITTER_PUSHER_PLUS,
    LINE_TRANSMITTER_GRABBER,
    LINE_TRANSMITTER_GRABBER_PLUS,
    ADVANCED_GREEDY_BLOCK,
    ADVANCED_IMPORT,
    ADVANCED_EXPORT,
    LINE_TRANSMITTER_VANILLA_PUSHER,
    LINE_TRANSMITTER_VANILLA_GRABBER,
    // models are not nodes, but they are included here for networks rake.
    MODEL,
    INPUT_ONLY_MONITOR,
    OUTPUT_ONLY_MONITOR
}
